### ISSUE TITLE
Output VEX documents?

### ISSUE THREAD

**Issue by nishakm** [nyph-infosec/daggerboard#15]
Could daggerboard generate VEX documents like the CSAF or CycloneDX documents?

**Comment by namtarb** [comment]
As of now, Daggerboard is on the ingestion side of the SBOM pipeline - meaning that it was only intended to ingest and analyze SBOMs and, in the future, VEX documents. Daggerboard does not currently support VEX ingestion, but this is on the list of features to add in the next phase of the project. 

There is a list of tools for generating VEX documents here: https://cyclonedx.org/tool-center/
