### ISSUE TITLE
Compile to docker?

### ISSUE THREAD

**Issue by dmuller104** [nyph-infosec/daggerboard#17]
I am trying to compile the source code into a new docker image. I'm struggling with setting up the environment. Is there a Dockerfile you use to create the docker image to compile on?

**Comment by kojak-a** [comment]
Hello @dmuller104, thanks for posting your issue. Can you provide us a few things to troubleshoot? 
1. The error you are encountering.
2. What OS and Version you are running on.
3. Version of Python.
