### ISSUE TITLE
Daggerboard NIST baseline Vulnerability Disclosure Report is available, if interested

### ISSUE THREAD

**Issue by rjb4standards** [nyph-infosec/daggerboard#18]
I've uploaded  NIST Vulnerability Disclosure Report (VDR) for Daggerboard;
https://raw.githubusercontent.com/rjb4standards/REA-Products/master/DaggerBoard_1_0_2-VDR.xml 

JSON version of NIST VDR is available here:
https://raw.githubusercontent.com/rjb4standards/REA-Products/master/DaggerBoard_1_0_2-VDR.json

**Comment by kojak-a** [comment]
Hi @rjb4standards thanks for providing the VDR our team will review.

**Comment by rjb4standards** [comment]
I'm happy to assist if needed. Also, CycloneDX also supports NIST VDR, if you prefer to use the CycloneDX SBOM format. I'm happy to support you if you decide to use REA's open-source VDR implementation.
