### ISSUE TITLE
Daggerboard could not upload spdx SBOM file in the docker container image

### ISSUE THREAD

**Issue by rhr407** [nyph-infosec/daggerboard#19]
I am having issues uploading the SBOM spdx file in the docker container image. I will be grateful if someone can help me with this issue. A screenshot is attached for understanding the issue in depth. 

Kind regards

![image](https://user-images.githubusercontent.com/26026993/210315228-5aff2d6f-c9e2-46b2-a9cf-07b5b848fe55.png)

**Comment by avishayil** [comment]
Same issue here

**Comment by rhr407** [comment]
any update on this issue?

**Comment by kojak-a** [comment]
@rhr407 thanks for posting this issue. Can you provide us with the log message?

**Comment by rhr407** [comment]
<img width="1844" alt="image" src="https://user-images.githubusercontent.com/26026993/217202711-79a9aa2e-f51d-4469-bf3d-51c45c875fc3.png">

**Comment by namtarb** [comment]
JSON SPDX is not currently supported by Daggerboard, but we are working on adding support. Based on my testing, I was only able to get the Microsoft tool to output JSON SPDX. In the meantime, tools for converting the SPDX format can be found here: https://spdx.dev/spdx-tools/. 

See the wiki for additional information on supported SPDX formats: https://github.com/nyph-infosec/daggerboard/wiki/Supported-SPDX-Formats-&-Upload-Troubleshooting.
